# config/meta.yml

meta_product_name: "Pant Forward"
meta_title: "Pant Forward - Pay it Forward, Recycle Bottles"
meta_description: "A company built on the idea that we can do better. Collect bottles, earn some quick cash, and save the environment in the process!"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
